### PR TITLE
Add handling of Unhandled error event

### PR DESCRIPTION
**Pull request by cjh980402**
Solution of https://github.com/play-dl/play-dl/issues/75

### CODE REVIEW

**Comment by killer069** [comment]
> Solution of #75

That error came from socket being closed. It has nothing to do with https_getter function.

Try yourself, Just create a stream and then close the socket by `res.socket.destroy`.

**Comment by cjh980402** [comment]
Then, how can I handle the unhandled erroe event(`Emitted 'error' event on ClientRequest`)?

**Comment by killer069** [comment]
@cjh980402 

Instead of doing that. Can you change

**Comment by killer069** [comment]
This will help to emit errors to response itself which will emit to AudioPlayer. So Error will be handled.

**Comment by cjh980402** [comment]
Wait I'll do some test of that code.

**Comment by killer069** [comment]
> Wait I'll do some test of that code.

Why didn't I added try and catch ?
That makes code little bit slow. So in most cases, I avoid using try and catch.

**Comment by cjh980402** [comment]
Using that code, `'error' event on ClientRequest` is still unhandled. Maybe error event is earlier runned than response callback.

**Comment by killer069** [comment]
> Using that code, `'error' event on ClientRequest` is still unhandled. Maybe error event is earlier emited than response callback.

How are you able to reproduce that error ??

I also want to test.

**Comment by cjh980402** [comment]
I tested two ways.
1. just wait when error occured.
2. disconnect the internet and run code.
```js
(await request_stream(test_url)).on("error", () => {
    console.log("error event");
  });
```

**Comment by killer069** [comment]
@cjh980402 

You are getting the errors in wrong way.

Try this :
```ts
let res = await request_stream(url)
res.on('error', (err) => console.log(err)) // Add this since stream also handle this.
res.resume() //Resume stream flow
setTimeout(() => {
        res.socket.emit('error', "Error: read ECONNRESET")
    }, 3000)
```

You will catch the error with that code.

**Comment by killer069** [comment]
Actually this is also not working. LOL

No actual fix, but you can prevent uncaughtException from exiting the bot :
```js
process.on('uncaughtException', function (err) {
    console.log('Uncaught');
});
```

**Comment by killer069** [comment]
Your try and catch is also not able to catch this error. So can't have fix for this.

You can try the above code. That will not exit from running the bot

**Comment by cjh980402** [comment]
I tested my code during 12hours, I can handle `ECONNRESET error` by AudioPlayer.
In my code `ECONNRESET error` emit under error on Stream.stream. So I can handle it by AudioPlayer.
```
Error: aborted
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketCloseListener (node:_http_client:407:19)
    at TLSSocket.emit (node:events:406:35)
    at node:net:672:12
    at TCP.done (node:_tls_wrap:580:7)
```
This aborted error is ECONNRESET error.

Also I added some optimization.
image

**Pull request closed without merging**
