### PR TITLE
Add unplayable video error

### PR DESCRIPTION
**Pull request by cjh980402**
Add unplayable video error when get video information.

### CODE REVIEW

**Comment by killer069** [comment]
@cjh980402 

Any url where this error occurs ??

**Comment by cjh980402** [comment]
I fount that https://www.youtube.com/watch?v=owtCcAis7DE here (maybe only for music premium).
However, I think there are better solution that normal and playable video is value of `player_response.playabilityStatus.status` is 'OK'.
So, I think throw error when `player_response.playabilityStatus.status !== 'OK'` is better solution.

**Comment by killer069** [comment]
> So, I think throw error when `player_response.playabilityStatus.status !== 'OK'` is better solution.

This is good solution.

**Comment by killer069** [comment]
will merge after adding some more changes.

**Comment by cjh980402** [comment]
Okay. Also, I find something
```js

**Comment by cjh980402** [comment]
```js
"playabilityStatus": {
        "status": "CONTENT_CHECK_REQUIRED",
        "errorScreen": {
            "playerErrorMessageRenderer": {
                "subreason": {
                    "runs": [{
                        "text": "보시는 분들의 주의가 필요합니다."
                    }]
                },
                "reason": {
                    "simpleText": "다음 콘텐츠는 YouTube 커뮤니티에 의해 일부 시청자에게 부적절하거나 불쾌감을 주는 것으로 확인되었습니다."
                },
                "proceedButton": {
                    "buttonRenderer": {
                        "style": "STYLE_OVERLAY",
                        "size": "SIZE_DEFAULT",
                        "isDisabled": false,
                        "text": {
                            "simpleText": "절차를 이해했으며 계속 진행하기 원합니다."
                        },
                        "serviceEndpoint": {
                            "clickTrackingParams": "CAEQ8FsiEwiRnNDpou3yAhXMVSoKHb0bBFs=",
                            "commandMetadata": {
                                "webCommandMetadata": {
                                    "sendPost": true,
                                    "apiUrl": "/youtubei/v1/verify_age"
                                }
                            },
                            "verifyAgeEndpoint": {
                                "nextEndpoint": {
                                    "clickTrackingParams": "CAEQ8FsiEwiRnNDpou3yAhXMVSoKHb0bBFs=",
                                    "commandMetadata": {
                                        "webCommandMetadata": {
                                            "url": "/watch?v=wZX06YCp-NY",
                                            "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
                                            "rootVe": 83769
                                        }
                                    },
                                    "urlEndpoint": {
                                        "url": "/watch?v=wZX06YCp-NY"
                                    }
                                },
                                "setControvercy": true
                            }
                        },
                        "trackingParams": "CAEQ8FsiEwiRnNDpou3yAhXMVSoKHb0bBFs="
                    }
                },
                "thumbnail": {
                    "thumbnails": [{
                        "url": "//s.ytimg.com/yts/img/meh7-vflGevej7.png",
                        "width": 140,
                        "height": 100
                    }]
                },
                "icon": {
                    "iconType": "ERROR_OUTLINE"
                }
            }
        },
        "contextParams": "Q0FFU0FnZ0I="
    }
```

```js
"playabilityStatus": {
        "status": "UNPLAYABLE",
        "reason": "Music Premium 회원만 시청할 수 있는 동영상입니다.",
        "errorScreen": {
            "playerErrorMessageRenderer": {
                "reason": {
                    "simpleText": "Music Premium 회원만 시청할 수 있는 동영상입니다."
                },
                "thumbnail": {
                    "thumbnails": [{
                        "url": "//s.ytimg.com/yts/img/meh7-vflGevej7.png",
                        "width": 140,
                        "height": 100
                    }]
                },
                "icon": {
                    "iconType": "ERROR_OUTLINE"
                }
            }
        },
        "playableInEmbed": true,
        "contextParams": "Q0FFU0FnZ0I=",
        "additionalLoggingData": "CPQD"
    }
```

```js
"playabilityStatus": {
        "status": "AGE_CHECK_REQUIRED",
        "reason": "본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다.",
        "errorScreen": {
            "playerKavRenderer": {
                "kavUrl": "https://ageverification.google.co.kr/ageverification?cl=2\u0026hl=ko\u0026prev=https://www.youtube.com/kav_complete?next_url=/watch%3Fv%3D-ZYCHfIA7wM",
                "playerParams": "OAE%3D",
                "title": "성인인증",
                "reason": {
                    "simpleText": "본 동영상은 만 19세 미만의 청소년이 이용할 수 없습니다. 성인인증 절차를 거치려면 한국 휴대전화 번호가 필요합니다."
                },
                "proceedButton": {
                    "buttonRenderer": {
                        "style": "STYLE_DARK_ON_BLACK",
                        "size": "SIZE_DEFAULT",
                        "isDisabled": false,
                        "text": {
                            "simpleText": "성인인증"
                        },
                        "navigationEndpoint": {
                            "clickTrackingParams": "CAEQ8FsiEwiIwey0o-3yAhXimMIKHQbxCkE=",
                            "commandMetadata": {
                                "webCommandMetadata": {
                                    "url": "https://ageverification.google.co.kr/ageverification?cl=2\u0026hl=ko\u0026prev=https://www.youtube.com/kav_complete?next_url=/watch%3Fv%3D-ZYCHfIA7wM",
                                    "webPageType": "WEB_PAGE_TYPE_UNKNOWN",
                                    "rootVe": 83769
                                }
                            },
                            "urlEndpoint": {
                                "url": "https://ageverification.google.co.kr/ageverification?cl=2\u0026hl=ko\u0026prev=https://www.youtube.com/kav_complete?next_url=/watch%3Fv%3D-ZYCHfIA7wM"
                            }
                        },
                        "trackingParams": "CAEQ8FsiEwiIwey0o-3yAhXimMIKHQbxCkE="
                    }
                },
                "thumbnail": {
                    "thumbnails": [{
                        "url": "//s.ytimg.com/yts/img/meh7-vflGevej7.png",
                        "width": 140,
                        "height": 100
                    }]
                },
                "icon": {
                    "iconType": "ERROR_OUTLINE"
                }
            }
        },
        "desktopLegacyAgeGateReason": 8,
        "contextParams": "Q0FFU0FnZ0I="
    }
```

```js
"playabilityStatus": {
        "status": "UNPLAYABLE",
        "reason": "동영상을 재생할 수 없음",
        "errorScreen": {
            "playerErrorMessageRenderer": {
                "subreason": {
                    "runs": [{
                        "text": "동영상을 볼 수 없습니다."
                    }]
                },
                "reason": {
                    "simpleText": "동영상을 재생할 수 없음"
                },
                "thumbnail": {
                    "thumbnails": [{
                        "url": "//s.ytimg.com/yts/img/meh7-vflGevej7.png",
                        "width": 140,
                        "height": 100
                    }]
                },
                "icon": {
                    "iconType": "ERROR_OUTLINE"
                }
            }
        },
        "contextParams": "Q0FFU0FnZ0I="
    }
```
This is what I see the playabilityStatus. Maybe we should change `player_response.playabilityStatus.reason || player_response.playabilityStatus.messages[0]` to other code.

**Comment by killer069** [comment]
> This is what I see the playabilityStatus. Maybe we should change `player_response.playabilityStatus.reason || player_response.playabilityStatus.messages[0]` to other code.

Other code like

**Comment by cjh980402** [comment]
`player_response.playabilityStatus.errorScreen.playerErrorMessageRenderer?.reason.simpleText ?? player_response.playabilityStatus.errorScreen.playerKavRenderer?.reason.simpleText`
this?

**Comment by cjh980402** [comment]
@killer069 Error message should change to 
```js
if(player_response.playabilityStatus.status !== 'OK')
    throw new Error(`While getting info from url\n${player_response.playabilityStatus.errorScreen.playerErrorMessageRenderer?.reason.simpleText ?? player_response.playabilityStatus.errorScreen.playerKavRenderer?.reason.simpleText}`)
```
from
```js
if(player_response.playabilityStatus.status !== 'OK')
    throw new Error(`While getting info from url\n${player_response.playabilityStatus.reason || player_response.playabilityStatus.messages[0]}`)
```

**Comment by killer069** [comment]
> @killer069 I think error message should change to
> 
> ```js
> if(player_response.playabilityStatus.status !== 'OK')
>     throw new Error(`While getting info from url\n${player_response.playabilityStatus.errorScreen.playerErrorMessageRenderer?.reason.simpleText ?? player_response.playabilityStatus.errorScreen.playerKavRenderer?.reason.simpleText}`)
> ```
> 
> from
> 
> ```js
> if(player_response.playabilityStatus.status !== 'OK')
>     throw new Error(`While getting info from url\n${player_response.playabilityStatus.reason || player_response.playabilityStatus.messages[0]}`)
> ```

Ok change it.

**Comment by cjh980402** [comment]
Then, you will change it or I make one more PR?

**Comment by killer069** [comment]
> Then, you will change it or I make one more PR?

I will change it once I release a stable spotify build in few hours.

**Pull request merged**
